package com.houseofcode.abdulg.login.models;

import android.os.Parcel;
import android.os.Parcelable;

import java.util.Date;

/**
 * Created by Abdullah on 13-09-2016.
 * Autogenerated parcelable
 */
public class Oat_Bran implements Parcelable {
    private Integer id;
    private Float amount;
    private Date created_at;
    private Date updated_at;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    public Date getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Float getAmount() {
        return amount;
    }

    public void setAmount(Float amount) {
        this.amount = amount;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeValue(this.amount);
        dest.writeLong(this.created_at != null ? this.created_at.getTime() : -1);
        dest.writeLong(this.updated_at != null ? this.updated_at.getTime() : -1);
    }

    public Oat_Bran() {
    }

    public Oat_Bran(Parcel in) {
        this.id = (Integer) in.readValue(Integer.class.getClassLoader());
        this.amount = (Float) in.readValue(Float.class.getClassLoader());
        long tmpCreated_at = in.readLong();
        this.created_at = tmpCreated_at == -1 ? null : new Date(tmpCreated_at);
        long tmpUpdated_at = in.readLong();
        this.updated_at = tmpUpdated_at == -1 ? null : new Date(tmpUpdated_at);
    }

    public static final Parcelable.Creator<Oat_Bran> CREATOR = new Parcelable.Creator<Oat_Bran>() {
        @Override
        public Oat_Bran createFromParcel(Parcel source) {
            return new Oat_Bran(source);
        }

        @Override
        public Oat_Bran[] newArray(int size) {
            return new Oat_Bran[size];
        }
    };
}